### ISSUE TITLE
Panning also zooms

### ISSUE THREAD

**Issue by stblassitude** [kivy-garden/garden.mapview#69]
I'm using the module on an RPi 3b with the RPi 7" touchscreen. Pinch zoom appears to work well, but using a single touch drag not only pans the map, but randomly zooms in or out.

I've not verified whether this is a general Kivy problem (but regular buttons appear to work as I would expect them to), or limited to mapview.

**Comment by tshirtman** [comment]
Can you run the touchtracer example and make sure that when you do the same kind of motion, you only get one, uninterrupted line. If that's not the case (two lines at the same time, or random cuts in the line) it could explain the issue.

**Comment by stblassitude** [comment]
It's happening with the touch tracer demo as well. I'm guessing it's either a general Kivy issue, or a hardware problem. I've added my problem to https://github.com/kivy/kivy/issues/4172.

**Comment by ocobacho** [comment]
I have the same problem on ubuntu and android I thinks is related to performance and workload because it tends to happen more on high zoom where more tiles are displayed and also if I have a lot of markers or things going on. When reducing MAX_WORKERS it tends to happen less. So it probably happens in the RPi 3b because of the low resources. Is there a way to optimize this?

**Comment by Dirk-Sandberg** [comment]
I'm seeing this as well when I try to pan on the MapView widget on iOS. Running the touch tracer demo shows only a single touch when I'm doing the same motion that causes zoom on a MapView.
